# Generated by Django 4.0.4 on 2022-06-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptoken',
            old_name='token',
            new_name='key',
        ),
    ]
