# Generated by Django 4.0.4 on 2022-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_token_apptoken_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptoken',
            name='key',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
